import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/theme-provider";
import { DirectionProvider } from "@/components/ui/direction";
import { cn } from "@/lib/utils";

const iranYekanX = localFont({
  src: "./fonts/IRANYekanXVF.woff2",
  weight: "100 900",
  style: "normal",
  display: "swap",
  variable: "--font-iranYekanX",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={cn("h-full", "antialiased", iranYekanX.className)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <DirectionProvider dir="rtl">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
